const labels = [
  'pessoa',
  'bicicleta',
  'carro',
  'motocicleta',
  'avião',
  'onibus',
  'trem',
  'caminhao',
  'barco',
  'semáforo',
  'hidrante',
  'sinal de pare',
  'parquímetro',
  'banco',
  'passaro',
  'gato',
  'cachorro',
  'cavalo',
  'ovelha',
  'vaca',
  'elefante',
  'urso',
  'zebra',
  'girafa',
  'mochila',
  'guarda-chuva',
  'Bolsa',
  'gravata',
  'mala de viagem',
  'frisbee',
  'esquis',
  'snowboard',
  'bola de esporte',
  'pipa',
  'taco de beisebol',
  'luva de baseball',
  'skate',
  'prancha de surfe',
  'raquete de tênis',
  'garrafa',
  'copo de vinho',
  'copo',
  'Forquilha',
  'faca',
  'colher',
  'tigela',
  'banana',
  'maçã',
  'sanduíche',
  'laranja',
  'brócolis',
  'cenoura',
  'cachorro quente',
  'pizza',
  'rosquinha',
  'bolo',
  'cadeira',
  'sofá',
  'vaso de planta',
  'cama',
  'mesa de jantar',
  'toalete',
  'televisão',
  'computador portátil',
  'rato',
  'controlo remoto',
  'teclado',
  'celular',
  'microondas',
  'forno',
  'torradeira',
  'lavatório',
  'frigorífico',
  'livro',
  'relógio',
  'vaso',
  'tesoura',
  'urso Teddy',
  'secador de cabelo',
  'escova de dente'
];

module.exports = labels;